HackBaseSite/HackBaseSite/Controllers/ViewHackIdeaController.cs
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HackBaseSite.Controllers
{
    public class ViewHackIdeaController : Controller
    {
        //
        // GET: /ViewHackIdea/id

        public ActionResult Index(string id)
        {
            MongoDB.Bson.ObjectId objectId = new MongoDB.Bson.ObjectId(id);
            var database = new MongoClient(IndexController.ConnectionString).GetServer().GetDatabase(IndexController.DatabaseName);
            var collection = database.GetCollection<Models.HackIdea_Id>("HackIdeas");

            var query = Query<Models.HackIdea_Id>.EQ(e => e.Id, objectId);
            Models.HackIdea_Id model = collection.FindOne(query);

            return View("hackPage",model);
        }

        [HttpPost]
        public ActionResult UpdateRepos(string id, string URL)
        {
            MongoDB.Bson.ObjectId objectId = new MongoDB.Bson.ObjectId(id);
            var database = new MongoClient(IndexController.ConnectionString).GetServer().GetDatabase(IndexController.DatabaseName);
            var collection = database.GetCollection<Models.HackIdea_Id>("HackIdeas");

            var query = Query<Models.HackIdea_Id>.EQ(e => e.Id, objectId);
            Models.HackIdea_Id model = collection.FindOne(query);

            model.GithubRepos += " "+URL;
            collection.Save(model);

            return View("hackPage", model);
        }

    }
}

HackBaseSite/HackBaseSite/Views/ViewHackIdea/hackPage.cshtml
@model Models.HackIdea_Id

@{
    ViewBag.Title = "Hack Page";
}
		<div class="row">
		<div class="span7 offset3">
		<h2>@Model.Name</h2>
		
	<div id="description">
  			Hack Name: @Model.Name<br>
  			Hack Description: @Model.Description<br>
  			Hack Author: @Model.Author<br>
  			Date Created: @Model.CreatedOn<br>
        Current GitHub Repositories: @Model.GithubRepos<br>
  			<u onclick="javascript:PostLike( '@Model.Id.ToString()' )"><a>I Like This Hack!</a></u> &nbsp; <span id="numbLikes">@Model.NumLikes</span> People Like This Hack<br>
  		<div id="navcontainer">
			<ul id="navlist">
                @{Html.RenderPartial("TagLink", Model.Tags);}
			</ul>
              Working on this hack? Link to your GitHub Repository Here: 
              @using (Html.BeginForm("UpdateRepos", "ViewHackIdea", FormMethod.Post, new { id="GitHubForm" }))
              {
                //@Html.TextBoxFor(f => f.GithubRepos, new { id = "Repos" });
                  <input type="text" id="Repos" name="URL" />
                  <input type="hidden" name="id" value="@Model.Id" />
              }
              <script type="text/javascript">
                  $(document).ready(function () {
                      $('#Repos').keypress(function (e) {
                          if (e.keyCode == 13)
                              $('#GitHubForm').submit();

                      });
                  });
            </script>
                    
		</div>
	</div>

		</div>
		</div>
<script type="text/javascript">
    function PostLike(Id) {
        $.ajax({
            type: "POST",
            url: "http://localhost:49407/Index/Like/"+Id,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: "{id: '"+Id+"', userId: '"+window.UserId+"'}",
            success: function (data) {
                var counter = $('#numbLikes');
                counter.text(data);
            },
            error: function (data) {
                var counter = $('#numbLikes');
                counter.text(data);
            }

        });
    }
</script>